image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -Version "$env:APPVEYOR_REPO_TAG_NAME" -CreatePackages $true -IsCI $true
test: off
deploy:
- provider: NuGet
  api_key:
    secure: cAB/DgarKTMghFXMglQssN6kzFiofX1iwr2zuZv2I2xHUav27xiaRpmw7YyEDKNN
  on:
    appveyor_repo_tag: true